/******************************************************************************
 * Filename:       UI_SERVICE.c
 *
 * Description:    This file contains the implementation of the service.
 *
 *                 Generated by:
 *                 BDS version: 1.1.3139.0
 *                 Plugin:      Texas Instruments BLE SDK GATT Server plugin 1.0.9
 *                 Time:        Fri Feb 16 2018 11:16:33 GMT+02:00
 *

 * Copyright (c) 2015-2017, Texas Instruments Incorporated
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * *  Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * *  Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * *  Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 **********************************************************************************/


/*********************************************************************
 * INCLUDES
 */
#include <string.h>

//#define xdc_runtime_Log_DISABLE_ALL 1  // Add to disable logs from this file
#include <xdc/runtime/Log.h>
#include <xdc/runtime/Diags.h>
#ifdef UARTLOG_ENABLE
#  include "UartLog.h"
#endif

#include <icall.h>
#include "util.h"
/* This Header file contains all BLE API and icall structure definition */
#include "icall_ble_api.h"

#include "ui_service.h"

/*********************************************************************
 * MACROS
 */

/*********************************************************************
 * CONSTANTS
 */

/*********************************************************************
 * TYPEDEFS
 */

/*********************************************************************
* GLOBAL VARIABLES
*/

// UI_SERVICE Service UUID
CONST uint8_t UiServiceUUID[ATT_BT_UUID_SIZE] =
{
  LO_UINT16(UI_SERVICE_SERV_UUID), HI_UINT16(UI_SERVICE_SERV_UUID)
};

// BUTTON UUID
CONST uint8_t us_BUTTONUUID[ATT_BT_UUID_SIZE] =
{
  LO_UINT16(US_BUTTON_UUID), HI_UINT16(US_BUTTON_UUID)
};

// VIBRATION UUID
CONST uint8_t us_VIBRATIONUUID[ATT_BT_UUID_SIZE] =
{
  LO_UINT16(US_VIBRATION_UUID), HI_UINT16(US_VIBRATION_UUID)
};

// LED UUID
CONST uint8_t us_LEDUUID[ATT_BT_UUID_SIZE] =
{
  LO_UINT16(US_LED_UUID), HI_UINT16(US_LED_UUID)
};


/*********************************************************************
 * LOCAL VARIABLES
 */

static UiServiceCBs_t *pAppCBs = NULL;
static uint8_t us_icall_rsp_task_id = INVALID_TASK_ID;

/*********************************************************************
* Profile Attributes - variables
*/

// Service declaration
static CONST gattAttrType_t UiServiceDecl = { ATT_BT_UUID_SIZE, UiServiceUUID };

// Characteristic "BUTTON" Properties (for declaration)
static uint8_t us_BUTTONProps = GATT_PROP_NOTIFY | GATT_PROP_READ;

// Characteristic "BUTTON" Value variable
static uint8_t us_BUTTONVal[US_BUTTON_LEN] = {0};

// Length of data in characteristic "BUTTON" Value variable, initialized to minimal size.
static uint16_t us_BUTTONValLen = US_BUTTON_LEN_MIN;

// Characteristic "BUTTON" Client Characteristic Configuration Descriptor
static gattCharCfg_t *us_BUTTONConfig;



// Characteristic "VIBRATION" Properties (for declaration)
static uint8_t us_VIBRATIONProps = GATT_PROP_NOTIFY | GATT_PROP_READ | GATT_PROP_WRITE | GATT_PROP_WRITE_NO_RSP;

// Characteristic "VIBRATION" Value variable
static uint8_t us_VIBRATIONVal[US_VIBRATION_LEN] = {0};

// Length of data in characteristic "VIBRATION" Value variable, initialized to minimal size.
static uint16_t us_VIBRATIONValLen = US_VIBRATION_LEN_MIN;

// Characteristic "VIBRATION" Client Characteristic Configuration Descriptor
static gattCharCfg_t *us_VIBRATIONConfig;



// Characteristic "LED" Properties (for declaration)
static uint8_t us_LEDProps = GATT_PROP_NOTIFY | GATT_PROP_READ | GATT_PROP_WRITE | GATT_PROP_WRITE_NO_RSP;

// Characteristic "LED" Value variable
static uint8_t us_LEDVal[US_LED_LEN] = {0};

// Length of data in characteristic "LED" Value variable, initialized to minimal size.
static uint16_t us_LEDValLen = US_LED_LEN_MIN;

// Characteristic "LED" Client Characteristic Configuration Descriptor
static gattCharCfg_t *us_LEDConfig;



/*********************************************************************
* Profile Attributes - Table
*/

static gattAttribute_t UI_SERVICEAttrTbl[] =
{
  // UI_SERVICE Service Declaration
  {
    { ATT_BT_UUID_SIZE, primaryServiceUUID },
    GATT_PERMIT_READ,
    0,
    (uint8_t *)&UiServiceDecl
  },
    // BUTTON Characteristic Declaration
    {
      { ATT_BT_UUID_SIZE, characterUUID },
      GATT_PERMIT_READ,
      0,
      &us_BUTTONProps
    },
      // BUTTON Characteristic Value
      {
        { ATT_BT_UUID_SIZE, us_BUTTONUUID },
        GATT_PERMIT_READ,
        0,
        us_BUTTONVal
      },
      // BUTTON CCCD
      {
        { ATT_BT_UUID_SIZE, clientCharCfgUUID },
        GATT_PERMIT_READ | GATT_PERMIT_WRITE,
        0,
        (uint8_t *)&us_BUTTONConfig
      },
      // BUTTON Characteristic User Description
      {
        { ATT_BT_UUID_SIZE, charUserDescUUID },
        GATT_PERMIT_READ,
        0,
        "Button pushed"
      },
    // VIBRATION Characteristic Declaration
    {
      { ATT_BT_UUID_SIZE, characterUUID },
      GATT_PERMIT_READ,
      0,
      &us_VIBRATIONProps
    },
      // VIBRATION Characteristic Value
      {
        { ATT_BT_UUID_SIZE, us_VIBRATIONUUID },
        GATT_PERMIT_READ | GATT_PERMIT_WRITE | GATT_PERMIT_WRITE,
        0,
        us_VIBRATIONVal
      },
      // VIBRATION CCCD
      {
        { ATT_BT_UUID_SIZE, clientCharCfgUUID },
        GATT_PERMIT_READ | GATT_PERMIT_WRITE,
        0,
        (uint8_t *)&us_VIBRATIONConfig
      },
      // VIBRATION Characteristic User Description
      {
        { ATT_BT_UUID_SIZE, charUserDescUUID },
        GATT_PERMIT_READ,
        0,
        "VIBRATION on/off"
      },
    // LED Characteristic Declaration
    {
      { ATT_BT_UUID_SIZE, characterUUID },
      GATT_PERMIT_READ,
      0,
      &us_LEDProps
    },
      // LED Characteristic Value
      {
        { ATT_BT_UUID_SIZE, us_LEDUUID },
        GATT_PERMIT_READ | GATT_PERMIT_WRITE | GATT_PERMIT_WRITE,
        0,
        us_LEDVal
      },
      // LED CCCD
      {
        { ATT_BT_UUID_SIZE, clientCharCfgUUID },
        GATT_PERMIT_READ | GATT_PERMIT_WRITE,
        0,
        (uint8_t *)&us_LEDConfig
      },
      // LED Characteristic User Description
      {
        { ATT_BT_UUID_SIZE, charUserDescUUID },
        GATT_PERMIT_READ,
        0,
        "LED on/off"
      },
};

/*********************************************************************
 * LOCAL FUNCTIONS
 */
static bStatus_t UI_SERVICE_ReadAttrCB( uint16_t connHandle, gattAttribute_t *pAttr,
                                           uint8_t *pValue, uint16_t *pLen, uint16_t offset,
                                           uint16_t maxLen, uint8_t method );
static bStatus_t UI_SERVICE_WriteAttrCB( uint16_t connHandle, gattAttribute_t *pAttr,
                                            uint8_t *pValue, uint16_t len, uint16_t offset,
                                            uint8_t method );

/*********************************************************************
 * PROFILE CALLBACKS
 */
// Simple Profile Service Callbacks
CONST gattServiceCBs_t UI_SERVICECBs =
{
  UI_SERVICE_ReadAttrCB,  // Read callback function pointer
  UI_SERVICE_WriteAttrCB, // Write callback function pointer
  NULL                       // Authorization callback function pointer
};

/*********************************************************************
* PUBLIC FUNCTIONS
*/

/*
 * UiService_AddService- Initializes the UiService service by registering
 *          GATT attributes with the GATT server.
 *
 *    rspTaskId - The ICall Task Id that should receive responses for Indications.
 */
extern bStatus_t UiService_AddService( uint8_t rspTaskId )
{
  uint8_t status;

  // Allocate Client Characteristic Configuration table
  us_BUTTONConfig = (gattCharCfg_t *)ICall_malloc( sizeof(gattCharCfg_t) * linkDBNumConns );
  if ( us_BUTTONConfig == NULL )
  {
    return ( bleMemAllocError );
  }

  // Initialize Client Characteristic Configuration attributes
  GATTServApp_InitCharCfg( INVALID_CONNHANDLE, us_BUTTONConfig );
  // Allocate Client Characteristic Configuration table
  us_VIBRATIONConfig = (gattCharCfg_t *)ICall_malloc( sizeof(gattCharCfg_t) * linkDBNumConns );
  if ( us_VIBRATIONConfig == NULL )
  {
    return ( bleMemAllocError );
  }

  // Initialize Client Characteristic Configuration attributes
  GATTServApp_InitCharCfg( INVALID_CONNHANDLE, us_VIBRATIONConfig );
  // Allocate Client Characteristic Configuration table
  us_LEDConfig = (gattCharCfg_t *)ICall_malloc( sizeof(gattCharCfg_t) * linkDBNumConns );
  if ( us_LEDConfig == NULL )
  {
    return ( bleMemAllocError );
  }

  // Initialize Client Characteristic Configuration attributes
  GATTServApp_InitCharCfg( INVALID_CONNHANDLE, us_LEDConfig );
  // Register GATT attribute list and CBs with GATT Server App
  status = GATTServApp_RegisterService( UI_SERVICEAttrTbl,
                                        GATT_NUM_ATTRS( UI_SERVICEAttrTbl ),
                                        GATT_MAX_ENCRYPT_KEY_SIZE,
                                        &UI_SERVICECBs );
  Log_info1("Registered service, %d attributes", (IArg)GATT_NUM_ATTRS( UI_SERVICEAttrTbl ));
  us_icall_rsp_task_id = rspTaskId;

  return ( status );
}

/*
 * UiService_RegisterAppCBs - Registers the application callback function.
 *                    Only call this function once.
 *
 *    appCallbacks - pointer to application callbacks.
 */
bStatus_t UiService_RegisterAppCBs( UiServiceCBs_t *appCallbacks )
{
  if ( appCallbacks )
  {
    pAppCBs = appCallbacks;
    Log_info1("Registered callbacks to application. Struct %p", (IArg)appCallbacks);
    return ( SUCCESS );
  }
  else
  {
    Log_warning0("Null pointer given for app callbacks.");
    return ( FAILURE );
  }
}

/*
 * UiService_SetParameter - Set a UiService parameter.
 *
 *    param - Profile parameter ID
 *    len   - length of data to write
 *    value - pointer to data to write.  This is dependent on
 *            the parameter ID and may be cast to the appropriate
 *            data type (example: data type of uint16_t will be cast to
 *            uint16_t pointer).
 */
bStatus_t UiService_SetParameter( uint8_t param, uint16_t len, void *value )
{
  bStatus_t ret = SUCCESS;
  uint8_t  *pAttrVal;
  uint16_t *pValLen;
  uint16_t valMinLen;
  uint16_t valMaxLen;
  uint8_t sendNotiInd = FALSE;
  gattCharCfg_t *attrConfig;
  uint8_t needAuth;

  switch ( param )
  {
    case US_BUTTON_ID:
      pAttrVal  =  us_BUTTONVal;
      pValLen   = &us_BUTTONValLen;
      valMinLen =  US_BUTTON_LEN_MIN;
      valMaxLen =  US_BUTTON_LEN;
      sendNotiInd = TRUE;
      attrConfig  = us_BUTTONConfig;
      needAuth    = FALSE; // Change if authenticated link is required for sending.
      Log_info2("SetParameter : %s len: %d", (IArg)"BUTTON", (IArg)len);
      break;

    case US_VIBRATION_ID:
      pAttrVal  =  us_VIBRATIONVal;
      pValLen   = &us_VIBRATIONValLen;
      valMinLen =  US_VIBRATION_LEN_MIN;
      valMaxLen =  US_VIBRATION_LEN;
      sendNotiInd = TRUE;
      attrConfig  = us_VIBRATIONConfig;
      needAuth    = FALSE; // Change if authenticated link is required for sending.
      Log_info2("SetParameter : %s len: %d", (IArg)"VIBRATION", (IArg)len);
      break;

    case US_LED_ID:
      pAttrVal  =  us_LEDVal;
      pValLen   = &us_LEDValLen;
      valMinLen =  US_LED_LEN_MIN;
      valMaxLen =  US_LED_LEN;
      sendNotiInd = TRUE;
      attrConfig  = us_LEDConfig;
      needAuth    = FALSE; // Change if authenticated link is required for sending.
      Log_info2("SetParameter : %s len: %d", (IArg)"LED", (IArg)len);
      break;

    default:
      Log_error1("SetParameter: Parameter #%d not valid.", (IArg)param);
      return INVALIDPARAMETER;
  }

  // Check bounds, update value and send notification or indication if possible.
  if ( len <= valMaxLen && len >= valMinLen )
  {
    memcpy(pAttrVal, value, len);
    *pValLen = len; // Update length for read and get.

    if (sendNotiInd)
    {
      Log_info2("Transmitting noti/ind- connHandle %d, %s", (IArg)attrConfig[0].connHandle,
                                                    (IArg)( (attrConfig[0].value==0)?"Noti/ind disabled":
                                                    (attrConfig[0].value==1)?"Notification enabled":
                                                     "Indication enabled" ) );
      // Try to send notification.
      GATTServApp_ProcessCharCfg( attrConfig, pAttrVal, needAuth,
                                  UI_SERVICEAttrTbl, GATT_NUM_ATTRS( UI_SERVICEAttrTbl ),
                                  us_icall_rsp_task_id,  UI_SERVICE_ReadAttrCB);
    }
  }
  else
  {
    Log_error3("Length outside bounds: Len: %d MinLen: %d MaxLen: %d.", (IArg)len, (IArg)valMinLen, (IArg)valMaxLen);
    ret = bleInvalidRange;
  }

  return ret;
}


/*
 * UiService_GetParameter - Get a UiService parameter.
 *
 *    param - Profile parameter ID
 *    len   - pointer to a variable that contains the maximum length that can be written to *value.
              After the call, this value will contain the actual returned length.
 *    value - pointer to data to write.  This is dependent on
 *            the parameter ID and may be cast to the appropriate
 *            data type (example: data type of uint16_t will be cast to
 *            uint16_t pointer).
 */
bStatus_t UiService_GetParameter( uint8_t param, uint16_t *len, void *value )
{
  bStatus_t ret = SUCCESS;
  switch ( param )
  {
    case US_VIBRATION_ID:
      *len = MIN(*len, us_VIBRATIONValLen);
      memcpy(value, us_VIBRATIONVal, *len);
      Log_info2("GetParameter : %s returning %d bytes", (IArg)"VIBRATION", (IArg)*len);
      break;

    case US_LED_ID:
      *len = MIN(*len, us_LEDValLen);
      memcpy(value, us_LEDVal, *len);
      Log_info2("GetParameter : %s returning %d bytes", (IArg)"LED", (IArg)*len);
      break;

    default:
      Log_error1("GetParameter: Parameter #%d not valid.", (IArg)param);
      ret = INVALIDPARAMETER;
      break;
  }
  return ret;
}

/*********************************************************************
 * @internal
 * @fn          UI_SERVICE_findCharParamId
 *
 * @brief       Find the logical param id of an attribute in the service's attr table.
 *
 *              Works only for Characteristic Value attributes and
 *              Client Characteristic Configuration Descriptor attributes.
 *
 * @param       pAttr - pointer to attribute
 *
 * @return      uint8_t paramID (ref UI_SERVICE.h) or 0xFF if not found.
 */
static uint8_t UI_SERVICE_findCharParamId(gattAttribute_t *pAttr)
{
  // Is this a Client Characteristic Configuration Descriptor?
  if (ATT_BT_UUID_SIZE == pAttr->type.len && GATT_CLIENT_CHAR_CFG_UUID == *(uint16_t *)pAttr->type.uuid)
    return UI_SERVICE_findCharParamId(pAttr - 1); // Assume the value attribute precedes CCCD and recurse

  // Is this attribute in "BUTTON"?
  else if ( ATT_BT_UUID_SIZE == pAttr->type.len && !memcmp(pAttr->type.uuid, us_BUTTONUUID, pAttr->type.len))
    return US_BUTTON_ID;

  // Is this attribute in "VIBRATION"?
  else if ( ATT_BT_UUID_SIZE == pAttr->type.len && !memcmp(pAttr->type.uuid, us_VIBRATIONUUID, pAttr->type.len))
    return US_VIBRATION_ID;

  // Is this attribute in "LED"?
  else if ( ATT_BT_UUID_SIZE == pAttr->type.len && !memcmp(pAttr->type.uuid, us_LEDUUID, pAttr->type.len))
    return US_LED_ID;

  else
    return 0xFF; // Not found. Return invalid.
}

/*********************************************************************
 * @fn          UI_SERVICE_ReadAttrCB
 *
 * @brief       Read an attribute.
 *
 * @param       connHandle - connection message was received on
 * @param       pAttr - pointer to attribute
 * @param       pValue - pointer to data to be read
 * @param       pLen - length of data to be read
 * @param       offset - offset of the first octet to be read
 * @param       maxLen - maximum length of data to be read
 * @param       method - type of read message
 *
 * @return      SUCCESS, blePending or Failure
 */
static bStatus_t UI_SERVICE_ReadAttrCB( uint16_t connHandle, gattAttribute_t *pAttr,
                                       uint8_t *pValue, uint16_t *pLen, uint16_t offset,
                                       uint16_t maxLen, uint8_t method )
{
  bStatus_t status = SUCCESS;
  uint16_t valueLen;
  uint8_t paramID = 0xFF;

  // Find settings for the characteristic to be read.
  paramID = UI_SERVICE_findCharParamId( pAttr );
  switch ( paramID )
  {
    case US_BUTTON_ID:
      valueLen = us_BUTTONValLen;

      Log_info4("ReadAttrCB : %s connHandle: %d offset: %d method: 0x%02x",
                 (IArg)"BUTTON",
                 (IArg)connHandle,
                 (IArg)offset,
                 (IArg)method);
      /* Other considerations for BUTTON can be inserted here */
      break;

    case US_VIBRATION_ID:
      valueLen = us_VIBRATIONValLen;

      Log_info4("ReadAttrCB : %s connHandle: %d offset: %d method: 0x%02x",
                 (IArg)"VIBRATION",
                 (IArg)connHandle,
                 (IArg)offset,
                 (IArg)method);
      /* Other considerations for VIBRATION can be inserted here */
      break;

    case US_LED_ID:
      valueLen = us_LEDValLen;

      Log_info4("ReadAttrCB : %s connHandle: %d offset: %d method: 0x%02x",
                 (IArg)"LED",
                 (IArg)connHandle,
                 (IArg)offset,
                 (IArg)method);
      /* Other considerations for LED can be inserted here */
      break;

    default:
      Log_error0("Attribute was not found.");
      return ATT_ERR_ATTR_NOT_FOUND;
  }
  // Check bounds and return the value
  if ( offset > valueLen )  // Prevent malicious ATT ReadBlob offsets.
  {
    Log_error0("An invalid offset was requested.");
    status = ATT_ERR_INVALID_OFFSET;
  }
  else
  {
    *pLen = MIN(maxLen, valueLen - offset);  // Transmit as much as possible
    memcpy(pValue, pAttr->pValue + offset, *pLen);
  }

  return status;
}

/*********************************************************************
 * @fn      UI_SERVICE_WriteAttrCB
 *
 * @brief   Validate attribute data prior to a write operation
 *
 * @param   connHandle - connection message was received on
 * @param   pAttr - pointer to attribute
 * @param   pValue - pointer to data to be written
 * @param   len - length of data
 * @param   offset - offset of the first octet to be written
 * @param   method - type of write message
 *
 * @return  SUCCESS, blePending or Failure
 */
static bStatus_t UI_SERVICE_WriteAttrCB( uint16_t connHandle, gattAttribute_t *pAttr,
                                        uint8_t *pValue, uint16_t len, uint16_t offset,
                                        uint8_t method )
{
  bStatus_t status  = SUCCESS;
  uint8_t   paramID = 0xFF;
  uint8_t   changeParamID = 0xFF;
  uint16_t writeLenMin;
  uint16_t writeLenMax;
  uint16_t *pValueLenVar;

  // See if request is regarding a Client Characterisic Configuration
  if (ATT_BT_UUID_SIZE == pAttr->type.len && GATT_CLIENT_CHAR_CFG_UUID == *(uint16_t *)pAttr->type.uuid)
  {
    // Allow notification and indication, but do not check if really allowed per CCCD.
    status = GATTServApp_ProcessCCCWriteReq( connHandle, pAttr, pValue, len,
                                             offset, GATT_CLIENT_CFG_NOTIFY |
                                                     GATT_CLIENT_CFG_INDICATE );
    if (SUCCESS == status && pAppCBs && pAppCBs->pfnCfgChangeCb)
       pAppCBs->pfnCfgChangeCb( connHandle, UI_SERVICE_SERV_UUID,
                                UI_SERVICE_findCharParamId(pAttr), pValue, len );

     return status;
  }

  // Find settings for the characteristic to be written.
  paramID = UI_SERVICE_findCharParamId( pAttr );
  switch ( paramID )
  {
    case US_VIBRATION_ID:
      writeLenMin  = US_VIBRATION_LEN_MIN;
      writeLenMax  = US_VIBRATION_LEN;
      pValueLenVar = &us_VIBRATIONValLen;

      Log_info5("WriteAttrCB : %s connHandle(%d) len(%d) offset(%d) method(0x%02x)",
                 (IArg)"VIBRATION",
                 (IArg)connHandle,
                 (IArg)len,
                 (IArg)offset,
                 (IArg)method);
      /* Other considerations for VIBRATION can be inserted here */
      break;

    case US_LED_ID:
      writeLenMin  = US_LED_LEN_MIN;
      writeLenMax  = US_LED_LEN;
      pValueLenVar = &us_LEDValLen;

      Log_info5("WriteAttrCB : %s connHandle(%d) len(%d) offset(%d) method(0x%02x)",
                 (IArg)"LED",
                 (IArg)connHandle,
                 (IArg)len,
                 (IArg)offset,
                 (IArg)method);
      /* Other considerations for LED can be inserted here */
      break;

    default:
      Log_error0("Attribute was not found.");
      return ATT_ERR_ATTR_NOT_FOUND;
  }
  // Check whether the length is within bounds.
  if ( offset >= writeLenMax )
  {
    Log_error0("An invalid offset was requested.");
    status = ATT_ERR_INVALID_OFFSET;
  }
  else if ( offset + len > writeLenMax )
  {
    Log_error0("Invalid value length was received.");
    status = ATT_ERR_INVALID_VALUE_SIZE;
  }
  else if ( offset + len < writeLenMin && ( method == ATT_EXECUTE_WRITE_REQ || method == ATT_WRITE_REQ ) )
  {
    // Refuse writes that are lower than minimum.
    // Note: Cannot determine if a Reliable Write (to several chars) is finished, so those will
    //       only be refused if this attribute is the last in the queue (method is execute).
    //       Otherwise, reliable writes are accepted and parsed piecemeal.
    Log_error0("Invalid value length was received.");
    status = ATT_ERR_INVALID_VALUE_SIZE;
  }
  else
  {
    // Copy pValue into the variable we point to from the attribute table.
    memcpy(pAttr->pValue + offset, pValue, len);

    // Only notify application and update length if enough data is written.
    //
    // Note: If reliable writes are used (meaning several attributes are written to using ATT PrepareWrite),
    //       the application will get a callback for every write with an offset + len larger than _LEN_MIN.
    // Note: For Long Writes (ATT Prepare + Execute towards only one attribute) only one callback will be issued,
    //       because the write fragments are concatenated before being sent here.
    if ( offset + len >= writeLenMin )
    {
      changeParamID = paramID;
      *pValueLenVar = offset + len; // Update data length.
    }
  }

  // Let the application know something changed (if it did) by using the
  // callback it registered earlier (if it did).
  if (changeParamID != 0xFF)
    if ( pAppCBs && pAppCBs->pfnChangeCb )
      pAppCBs->pfnChangeCb( connHandle, UI_SERVICE_SERV_UUID, paramID, pValue, len+offset ); // Call app function from stack task context.

  return status;
}
